from __future__ import annotations

import os
from typing import Callable


ResponseGenerator = Callable[[str], str]


def deterministic_response_fallback(prompt: str) -> str:
    return (
        "This response was not generated by an LLM because no live response "
        "generator was supplied. The runtime boundary is working; replace this "
        "fallback with an injected LLM generator when running live deliberations."
    )


def generate_response_text(
    *,
    prompt: str,
    response_generator: ResponseGenerator | None = None,
) -> str:
    if response_generator is not None:
        return response_generator(prompt)

    return deterministic_response_fallback(prompt)


def openai_response_generator(prompt: str) -> str:
    from openai import OpenAI

    model = os.environ["OPENAI_MODEL"]
    client = OpenAI()

    response = client.responses.create(
        model=model,
        input=prompt,
    )

    return response.output_text.strip()